In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [2]:
# Creamos los DF
df_patients = pd.read_csv("healthpredict_patients.csv")
df_visits = pd.read_csv("healthpredict_visits.csv")

In [3]:
# Verificamos los tipos de datos de cada columna
df_patients

     patient_id              name  age gender region
0          1000      Lucía Romero   59      F    Sur
1          1001  Martina González   61      F  Norte
2          1002        Tomás Cruz   64      M   Este
3          1003     Benjamín Díaz   27      M    Sur
4          1004       Tomás Pérez   30      M  Oeste
..          ...               ...  ...    ...    ...
195        1195    Sofía González   54      F   Este
196        1196      Tomás Romero   52      M   Este
197        1197  Isabella Sánchez   38      F  Oeste
198        1198      Agustín Díaz   31      F   Este
199        1199     Isabella Díaz   41      M   Este

[200 rows x 5 columns]

In [4]:
df_visits

,visit_id,patient_id,visit_date,bmi,glucose,blood_pressure_sys,condition,outcome_risk
0,5000,1090,2025-03-18,26.5,103.7,151,Obesidad,1
1,5001,1155,2024-05-27,21.7,105.0,118,Ninguna,0
2,5002,1051,2024-06-17,28.3,90.4,143,Ninguna,0
3,5003,1137,2024-09-19,18.5,115.5,149,Hipertensión,0
4,5004,1168,2024-03-12,11.2,86.8,104,Ninguna,0
...,...,...,...,...,...,...,...,...
995,5995,1038,2024-05-03,30.1,120.6,110,Hipertensión,0
996,5996,1143,2025-08-19,26.1,91.7,110,Diabetes,0
997,5997,1078,2024-08-30,26.3,90.1,127,Ninguna,0
998,5998,1178,2024-08-20,26.7,120.8,119,Obesidad,0
999,5999,1039,2024-03-31,32.8,119.4,132,Hipertensión,0

In [5]:
# Creamos el DF todo unido
merged = df_visits.merge(df_patients, left_on='visit_id', right_on='patient_id', how='left')
merged

,visit_id,patient_id_x,visit_date,bmi,glucose,blood_pressure_sys,condition,outcome_risk,patient_id_y,name,age,gender,region
0,5000,1090,2025-03-18,26.5,103.7,151,Obesidad,1,NaN,NaN,NaN,NaN,NaN
1,5001,1155,2024-05-27,21.7,105.0,118,Ninguna,0,NaN,NaN,NaN,NaN,NaN
2,5002,1051,2024-06-17,28.3,90.4,143,Ninguna,0,NaN,NaN,NaN,NaN,NaN
3,5003,1137,2024-09-19,18.5,115.5,149,Hipertensión,0,NaN,NaN,NaN,NaN,NaN
4,5004,1168,2024-03-12,11.2,86.8,104,Ninguna,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,5995,1038,2024-05-03,30.1,120.6,110,Hipertensión,0,NaN,NaN,NaN,NaN,NaN
996,5996,1143,2025-08-19,26.1,91.7,110,Diabetes,0,NaN,NaN,NaN,NaN,NaN
997,5997,1078,2024-08-30,26.3,90.1,127,Ninguna,0,NaN,NaN,NaN,NaN,NaN
998,5998,1178,2024-08-20,26.7,120.8,119,Obesidad,0,NaN,NaN,NaN,NaN,NaN
999,5999,1039,2024-03-31,32.8,119.4,132,Hipertensión,0,NaN,NaN,NaN,NaN,NaN